// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const locale = {
    'topBarTitle': 'Community Admin Panel',
    'welcome': 'Welcome',
    'yes': 'yes',
    'no': 'No',
    'search': 'Search',
    'action': 'Acción',
    'requiredField': 'Required field',
    'removerItemGrid': 'Are you sure you want to delete the record?',
    'seeDetailsItemGrid': 'See details',
    'menu': {
        'seguridad': {
            'roles': 'roles',
            'users': 'users',
        },
    },
} as const;

export type LocaleKey = string;

export default locale;