// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const locale = {
    'topBarTitle': 'Comunidad Admin Panel',
    'welcome': 'Bienvenido',
    'yes': 'Si',
    'no': 'No',
    'search': 'Buscar',
    'action': 'Acción',
    'requiredField': 'Campo requerido',
    'removerItemGrid': '¿Esta seguro de eliminar el registro?',
    'seeDetailsItemGrid': 'Ver detalle',
    'menu': {
        'seguridad': {
            'roles': 'roles',
            'users': 'usuarios',
        },
    },
} as const;

export type LocaleKey = string;

export default locale;